// This file is auto-generated by @hey-api/openapi-ts

import { type Options, uploadMedia, addCategory, getCategories, addBag, getAllBags, updateBag, deleteBagById } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError, infiniteQueryOptions, type InfiniteData } from '@tanstack/react-query';
import type { UploadMediaData, UploadMediaResponse, AddCategoryData, AddCategoryResponse, GetCategoriesData, AddBagData, AddBagResponse, GetAllBagsData, GetAllBagsResponse, UpdateBagData, UpdateBagResponse, DeleteBagByIdData, DeleteBagByIdResponse } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const uploadMediaQueryKey = (options: Options<UploadMediaData>) => createQueryKey('uploadMedia', options);

export const uploadMediaOptions = (options: Options<UploadMediaData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await uploadMedia({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: uploadMediaQueryKey(options)
    });
};

export const uploadMediaMutation = (options?: Partial<Options<UploadMediaData>>): UseMutationOptions<UploadMediaResponse, DefaultError, Options<UploadMediaData>> => {
    const mutationOptions: UseMutationOptions<UploadMediaResponse, DefaultError, Options<UploadMediaData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await uploadMedia({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const addCategoryQueryKey = (options: Options<AddCategoryData>) => createQueryKey('addCategory', options);

export const addCategoryOptions = (options: Options<AddCategoryData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await addCategory({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addCategoryQueryKey(options)
    });
};

export const addCategoryMutation = (options?: Partial<Options<AddCategoryData>>): UseMutationOptions<AddCategoryResponse, DefaultError, Options<AddCategoryData>> => {
    const mutationOptions: UseMutationOptions<AddCategoryResponse, DefaultError, Options<AddCategoryData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await addCategory({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCategoriesQueryKey = (options?: Options<GetCategoriesData>) => createQueryKey('getCategories', options);

export const getCategoriesOptions = (options?: Options<GetCategoriesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCategories({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCategoriesQueryKey(options)
    });
};

export const addBagQueryKey = (options: Options<AddBagData>) => createQueryKey('addBag', options);

export const addBagOptions = (options: Options<AddBagData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await addBag({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addBagQueryKey(options)
    });
};

export const addBagMutation = (options?: Partial<Options<AddBagData>>): UseMutationOptions<AddBagResponse, DefaultError, Options<AddBagData>> => {
    const mutationOptions: UseMutationOptions<AddBagResponse, DefaultError, Options<AddBagData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await addBag({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllBagsQueryKey = (options?: Options<GetAllBagsData>) => createQueryKey('getAllBags', options);

export const getAllBagsOptions = (options?: Options<GetAllBagsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAllBags({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAllBagsQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = queryKey[0];
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getAllBagsInfiniteQueryKey = (options?: Options<GetAllBagsData>): QueryKey<Options<GetAllBagsData>> => createQueryKey('getAllBags', options, true);

export const getAllBagsInfiniteOptions = (options?: Options<GetAllBagsData>) => {
    return infiniteQueryOptions<GetAllBagsResponse, DefaultError, InfiniteData<GetAllBagsResponse>, QueryKey<Options<GetAllBagsData>>, number | Pick<QueryKey<Options<GetAllBagsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetAllBagsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getAllBags({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAllBagsInfiniteQueryKey(options)
    });
};

export const updateBagMutation = (options?: Partial<Options<UpdateBagData>>): UseMutationOptions<UpdateBagResponse, DefaultError, Options<UpdateBagData>> => {
    const mutationOptions: UseMutationOptions<UpdateBagResponse, DefaultError, Options<UpdateBagData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await updateBag({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteBagByIdMutation = (options?: Partial<Options<DeleteBagByIdData>>): UseMutationOptions<DeleteBagByIdResponse, DefaultError, Options<DeleteBagByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteBagByIdResponse, DefaultError, Options<DeleteBagByIdData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteBagById({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};