// This file is auto-generated by @hey-api/openapi-ts

import { type Options, addCategory, addBag } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { AddCategoryData, AddCategoryResponse, AddBagData, AddBagResponse } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const addCategoryQueryKey = (options: Options<AddCategoryData>) => createQueryKey('addCategory', options);

export const addCategoryOptions = (options: Options<AddCategoryData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await addCategory({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addCategoryQueryKey(options)
    });
};

export const addCategoryMutation = (options?: Partial<Options<AddCategoryData>>): UseMutationOptions<AddCategoryResponse, DefaultError, Options<AddCategoryData>> => {
    const mutationOptions: UseMutationOptions<AddCategoryResponse, DefaultError, Options<AddCategoryData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await addCategory({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const addBagQueryKey = (options: Options<AddBagData>) => createQueryKey('addBag', options);

export const addBagOptions = (options: Options<AddBagData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await addBag({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addBagQueryKey(options)
    });
};

export const addBagMutation = (options?: Partial<Options<AddBagData>>): UseMutationOptions<AddBagResponse, DefaultError, Options<AddBagData>> => {
    const mutationOptions: UseMutationOptions<AddBagResponse, DefaultError, Options<AddBagData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await addBag({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};