// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-fetch';
import type { GetCurrentUserData, GetCurrentUserResponse, UpdateUserByIdData, UpdateUserByIdResponse, GetAllUsersData, GetAllUsersResponse, GetOrderByIdData, GetOrderByIdResponse, GetAllOrdersData, GetAllOrdersResponse, GetAllOrdersForAdminData, GetAllOrdersForAdminResponse, GetOrderDetailsByOrderIdForAdminData, GetOrderDetailsByOrderIdForAdminResponse, UpdateOrderStatusData, UpdateOrderStatusResponse, GetAllOrdersOfUserForAdminData, GetAllOrdersOfUserForAdminResponse, UploadMediaData, UploadMediaResponse, SearchData, SearchError, InitiateEsewaPaymentData, InitiateEsewaPaymentResponse, VerifyEsewaPaymentData, VerifyEsewaPaymentResponse, CreatePaymentIntentData, CreatePaymentIntentResponse, AddCategoryData, AddCategoryResponse, GetCategoriesData, GetCategoriesResponse, GetCategoriesWithBagsData, GetCategoriesWithBagsResponse, AddToCartData, AddToCartResponse, RemoveFromCartData, RemoveFromCartResponse, UpdateCartData, UpdateCartResponse, GetCartData, GetCartResponse, AddBagData, AddBagResponse, GetAllBagsData, GetAllBagsResponse, GetBagByIdData, GetBagByIdResponse, UpdateBagData, UpdateBagResponse, DeleteBagByIdData, DeleteBagByIdResponse, SearchBagsData, SearchBagsResponse, GetBagsByCategoryIdData, GetBagsByCategoryIdResponse, VerifyOtpData, VerifyOtpResponse, ResendOtpData, ResendOtpResponse, RegisterUserData, RegisterUserResponse, LoginUserData, LoginUserResponse, LogoutData, LogoutResponse, ResetPasswordData, ResetPasswordResponse, RecoverPasswordData, RecoverPasswordResponse, RefreshTokenData, RefreshTokenResponse, GoogleAuthData, GoogleAuthResponse, GoogleCallBackData, GoogleCallBackResponse, GetDashboardAnalyticsData, GetDashboardAnalyticsResponse, AdminLoginData, AdminLoginResponse, RevokeUserSessionData, RevokeUserSessionResponse, BanUserData, BanUserResponse, UnbanUserData, UnbanUserResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCurrentUserResponse, unknown, ThrowOnError>({
        url: '/user/me',
        ...options
    });
};

export const updateUserById = <ThrowOnError extends boolean = false>(options: Options<UpdateUserByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateUserByIdResponse, unknown, ThrowOnError>({
        url: '/user/update-me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllUsersResponse, unknown, ThrowOnError>({
        url: '/user/all-users',
        ...options
    });
};

export const getOrderById = <ThrowOnError extends boolean = false>(options: Options<GetOrderByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetOrderByIdResponse, unknown, ThrowOnError>({
        url: '/order/get-order-by-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getAllOrders = <ThrowOnError extends boolean = false>(options?: Options<GetAllOrdersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllOrdersResponse, unknown, ThrowOnError>({
        url: '/order/get-all-orders',
        ...options
    });
};

export const getAllOrdersForAdmin = <ThrowOnError extends boolean = false>(options?: Options<GetAllOrdersForAdminData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllOrdersForAdminResponse, unknown, ThrowOnError>({
        url: '/order/admin/get-all-orders',
        ...options
    });
};

export const getOrderDetailsByOrderIdForAdmin = <ThrowOnError extends boolean = false>(options: Options<GetOrderDetailsByOrderIdForAdminData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetOrderDetailsByOrderIdForAdminResponse, unknown, ThrowOnError>({
        url: '/order/admin/get-order-details/{orderId}',
        ...options
    });
};

export const updateOrderStatus = <ThrowOnError extends boolean = false>(options: Options<UpdateOrderStatusData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UpdateOrderStatusResponse, unknown, ThrowOnError>({
        url: '/order/admin/update-order-status',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getAllOrdersOfUserForAdmin = <ThrowOnError extends boolean = false>(options: Options<GetAllOrdersOfUserForAdminData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAllOrdersOfUserForAdminResponse, unknown, ThrowOnError>({
        url: '/order/admin/get-user-orders/{userId}',
        ...options
    });
};

export const uploadMedia = <ThrowOnError extends boolean = false>(options: Options<UploadMediaData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UploadMediaResponse, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/media/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

export const search = <ThrowOnError extends boolean = false>(options: Options<SearchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, SearchError, ThrowOnError>({
        url: '/gemini/search',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const initiateEsewaPayment = <ThrowOnError extends boolean = false>(options: Options<InitiateEsewaPaymentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<InitiateEsewaPaymentResponse, unknown, ThrowOnError>({
        url: '/payment/esewa/initiate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const verifyEsewaPayment = <ThrowOnError extends boolean = false>(options: Options<VerifyEsewaPaymentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<VerifyEsewaPaymentResponse, unknown, ThrowOnError>({
        url: '/payment/esewa/payment-verify',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const createPaymentIntent = <ThrowOnError extends boolean = false>(options: Options<CreatePaymentIntentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreatePaymentIntentResponse, unknown, ThrowOnError>({
        url: '/checkout/create-payment-intent',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const addCategory = <ThrowOnError extends boolean = false>(options: Options<AddCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddCategoryResponse, unknown, ThrowOnError>({
        url: '/category/add-category',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getCategories = <ThrowOnError extends boolean = false>(options?: Options<GetCategoriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCategoriesResponse, unknown, ThrowOnError>({
        url: '/category/get-categories',
        ...options
    });
};

export const getCategoriesWithBags = <ThrowOnError extends boolean = false>(options: Options<GetCategoriesWithBagsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCategoriesWithBagsResponse, unknown, ThrowOnError>({
        url: '/category/get-categories-with-bags',
        ...options
    });
};

export const addToCart = <ThrowOnError extends boolean = false>(options: Options<AddToCartData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddToCartResponse, unknown, ThrowOnError>({
        url: '/cart/add-to-cart',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const removeFromCart = <ThrowOnError extends boolean = false>(options: Options<RemoveFromCartData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<RemoveFromCartResponse, unknown, ThrowOnError>({
        url: '/cart/remove-from-cart',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const updateCart = <ThrowOnError extends boolean = false>(options: Options<UpdateCartData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateCartResponse, unknown, ThrowOnError>({
        url: '/cart/update-cart',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getCart = <ThrowOnError extends boolean = false>(options?: Options<GetCartData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCartResponse, unknown, ThrowOnError>({
        url: '/cart/get-cart',
        ...options
    });
};

export const addBag = <ThrowOnError extends boolean = false>(options: Options<AddBagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddBagResponse, unknown, ThrowOnError>({
        url: '/bag/add-bag',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getAllBags = <ThrowOnError extends boolean = false>(options?: Options<GetAllBagsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllBagsResponse, unknown, ThrowOnError>({
        url: '/bag/get-all-bags',
        ...options
    });
};

export const getBagById = <ThrowOnError extends boolean = false>(options: Options<GetBagByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetBagByIdResponse, unknown, ThrowOnError>({
        url: '/bag/get-bag/{id}',
        ...options
    });
};

export const updateBag = <ThrowOnError extends boolean = false>(options: Options<UpdateBagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateBagResponse, unknown, ThrowOnError>({
        url: '/bag/update-bag/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const deleteBagById = <ThrowOnError extends boolean = false>(options: Options<DeleteBagByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteBagByIdResponse, unknown, ThrowOnError>({
        url: '/bag/delete-bag/{id}',
        ...options
    });
};

export const searchBags = <ThrowOnError extends boolean = false>(options: Options<SearchBagsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<SearchBagsResponse, unknown, ThrowOnError>({
        url: '/bag/search',
        ...options
    });
};

export const getBagsByCategoryId = <ThrowOnError extends boolean = false>(options: Options<GetBagsByCategoryIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetBagsByCategoryIdResponse, unknown, ThrowOnError>({
        url: '/bag/categorized-bags',
        ...options
    });
};

export const verifyOtp = <ThrowOnError extends boolean = false>(options: Options<VerifyOtpData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<VerifyOtpResponse, unknown, ThrowOnError>({
        url: '/auth/verify-otp',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const resendOtp = <ThrowOnError extends boolean = false>(options: Options<ResendOtpData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ResendOtpResponse, unknown, ThrowOnError>({
        url: '/auth/resend-otp',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const registerUser = <ThrowOnError extends boolean = false>(options: Options<RegisterUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterUserResponse, unknown, ThrowOnError>({
        url: '/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const loginUser = <ThrowOnError extends boolean = false>(options: Options<LoginUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginUserResponse, unknown, ThrowOnError>({
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<LogoutResponse, unknown, ThrowOnError>({
        url: '/auth/logout',
        ...options
    });
};

export const resetPassword = <ThrowOnError extends boolean = false>(options: Options<ResetPasswordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ResetPasswordResponse, unknown, ThrowOnError>({
        url: '/auth/reset-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const recoverPassword = <ThrowOnError extends boolean = false>(options: Options<RecoverPasswordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RecoverPasswordResponse, unknown, ThrowOnError>({
        url: '/auth/recover-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const refreshToken = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokenData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<RefreshTokenResponse, unknown, ThrowOnError>({
        url: '/auth/refresh-token',
        ...options
    });
};

export const googleAuth = <ThrowOnError extends boolean = false>(options?: Options<GoogleAuthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GoogleAuthResponse, unknown, ThrowOnError>({
        url: '/auth/google',
        ...options
    });
};

export const googleCallBack = <ThrowOnError extends boolean = false>(options?: Options<GoogleCallBackData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GoogleCallBackResponse, unknown, ThrowOnError>({
        url: '/auth/google/callback',
        ...options
    });
};

export const getDashboardAnalytics = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardAnalyticsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDashboardAnalyticsResponse, unknown, ThrowOnError>({
        url: '/auth/admin/analytics/dashboard',
        ...options
    });
};

export const adminLogin = <ThrowOnError extends boolean = false>(options: Options<AdminLoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AdminLoginResponse, unknown, ThrowOnError>({
        url: '/auth/admin/admin-login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const revokeUserSession = <ThrowOnError extends boolean = false>(options: Options<RevokeUserSessionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RevokeUserSessionResponse, unknown, ThrowOnError>({
        url: '/auth/admin/revoke-session',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const banUser = <ThrowOnError extends boolean = false>(options: Options<BanUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<BanUserResponse, unknown, ThrowOnError>({
        url: '/auth/admin/ban-user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const unbanUser = <ThrowOnError extends boolean = false>(options: Options<UnbanUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UnbanUserResponse, unknown, ThrowOnError>({
        url: '/auth/admin/unban-user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};