// This file is auto-generated by @hey-api/openapi-ts

export type DeviceInfoEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    os: string;
    browser: string;
    device: string;
};

export type UserEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    googleId: string;
    email: string;
    fullName: string;
    password: string;
    isOauth: boolean;
    provider: string;
    isEmailVerified: boolean;
    emailVerificationToken: string;
    emailVerificationTokenExpiresAt: string | null;
    refreshToken: string;
    deviceInfo: DeviceInfoEntity;
    cart: CartEntity;
    orders: Array<OrderEntity>;
};

export type CartEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    user: UserEntity;
    cartItems: Array<CartItemEntity>;
};

export type BagEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    name: string;
    price: number;
    description: string;
    categories: Array<Category>;
    bagImages: Array<MediaEntity>;
};

export type Category = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    categoryName: string;
    bags: Array<BagEntity>;
};

export type MediaEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    image: string;
    altText?: string;
    bag: BagEntity;
};

export type CartItemEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    cart: CartEntity;
    bag: BagEntity;
    quantity: number;
};

export type OrderEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    user: UserEntity;
    status: 'pending' | 'paid' | 'failed' | 'refunded';
    deliveryMethod: 'delivery' | 'pickup';
    currency: string;
    amount: number;
    items?: Array<OrderItemEntity>;
    stripePaymentIntentId?: string;
    stripeChargeId?: string;
    itemsSnapShot?: unknown;
};

export type OrderItemEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    order: OrderEntity;
    bag: BagEntity;
    quantity: number;
    unitPrice: number;
};

export type CreateCategoryValidator = {
    categoryName: string;
};

export type AddToCartValidator = {
    bagId: string;
    quantity: number;
};

export type AddBagValidator = {
    name: string;
    price: number;
    description: string;
    categories: Array<string>;
};

export type UpdateBagValidator = {
    name?: string;
    price?: number;
    description?: string;
    categories?: Array<string>;
    bagImages?: Array<string>;
};

export type UserResponseData = {
    email: string;
    fullName: string;
};

export type RegisterResponse = {
    success: boolean;
    message: string;
    accessToken?: string;
    refreshToken?: string;
    data: {
        user: UserResponseData;
    };
};

export type RegisterUserDto = {
    fullName: string;
    email: string;
    password: string;
};

export type LoginValidator = {
    email: string;
    password: string;
    rememberMe?: boolean;
    os: string;
    browser: string;
    device: string;
    location: string;
};

export type GetUserByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type GetUserByIdResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        data: {
            updatedAt: string;
            createdAt: string;
            provider: string;
            isOauth: boolean;
            isEmailVerified: boolean;
            fullName: string;
            email: string;
        };
        message: string;
        success: boolean;
    };
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserByIdData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/user/update-me';
};

export type UpdateUserByIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        data: {
            fullName: string;
        };
        message: string;
        success: boolean;
    };
};

export type UpdateUserByIdResponse = UpdateUserByIdResponses[keyof UpdateUserByIdResponses];

export type GetOrderByIdData = {
    body: {
        orderId?: string;
    };
    path?: never;
    query?: never;
    url: '/order/get-order-by-id';
};

export type GetOrderByIdResponses = {
    /**
     * Ok
     */
    200: {
        data: OrderEntity;
        message: string;
        success: boolean;
    };
};

export type GetOrderByIdResponse = GetOrderByIdResponses[keyof GetOrderByIdResponses];

export type GetAllOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/order/get-all-orders';
};

export type GetAllOrdersResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            orders: Array<{
                deletedAt: string;
                updatedAt: string;
                createdAt: string;
                id: string;
                itemsSnapShot?: unknown;
                amount: number;
                currency: string;
                deliveryMethod: 'delivery' | 'pickup';
                status: 'pending' | 'paid' | 'failed' | 'refunded';
                user: UserEntity;
                items: Array<{
                    bag: {
                        images: Array<{
                            url: string;
                            id: string;
                        }>;
                        price: number;
                        name: string;
                        id: string;
                    };
                    unitPrice: number;
                    quantity: number;
                    id: string;
                }>;
            }>;
        };
        message: string;
        success: boolean;
    };
};

export type GetAllOrdersResponse = GetAllOrdersResponses[keyof GetAllOrdersResponses];

export type UploadMediaData = {
    body: {
        bagId: string;
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/media/upload';
};

export type UploadMediaResponses = {
    /**
     * Ok
     */
    200: {
        data?: unknown;
        message: string;
        success: boolean;
    } | {
        data: MediaEntity;
        message: string;
        success: boolean;
    };
};

export type UploadMediaResponse = UploadMediaResponses[keyof UploadMediaResponses];

export type CreatePaymentIntentData = {
    body: {
        deliveryMethod?: 'delivery' | 'pickup';
    };
    path?: never;
    query?: never;
    url: '/checkout/create-payment-intent';
};

export type CreatePaymentIntentResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            clientSecret?: unknown;
            message: string;
            deliveryMethod: 'delivery' | 'pickup';
            orderId: string;
        } | {
            message?: unknown;
            deliveryMethod: 'delivery' | 'pickup';
            clientSecret: string;
            orderId: string;
        };
        message: string;
        success: boolean;
    };
};

export type CreatePaymentIntentResponse = CreatePaymentIntentResponses[keyof CreatePaymentIntentResponses];

export type AddCategoryData = {
    body: CreateCategoryValidator;
    path?: never;
    query?: never;
    url: '/category/add-category';
};

export type AddCategoryResponses = {
    /**
     * Ok
     */
    200: {
        data: Category;
        message: string;
        success: boolean;
    };
};

export type AddCategoryResponse = AddCategoryResponses[keyof AddCategoryResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/category/get-categories';
};

export type GetCategoriesResponses = {
    /**
     * Ok
     */
    200: {
        data: Array<Category>;
        message: string;
        success: boolean;
    };
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type GetCategoriesWithBagsData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        limit: number;
    };
    url: '/category/get-categories-with-bags';
};

export type GetCategoriesWithBagsResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            totalPages: number;
            page: number;
            total: number;
            data: Array<Category>;
        };
        message: string;
        success: boolean;
    };
};

export type GetCategoriesWithBagsResponse = GetCategoriesWithBagsResponses[keyof GetCategoriesWithBagsResponses];

export type AddToCartData = {
    body: AddToCartValidator;
    path?: never;
    query?: never;
    url: '/cart/add-to-cart';
};

export type AddToCartResponses = {
    /**
     * Ok
     */
    200: {
        data: CartEntity;
        message: string;
    };
};

export type AddToCartResponse = AddToCartResponses[keyof AddToCartResponses];

export type RemoveFromCartData = {
    body: {
        userId?: string;
        bagId: string;
    };
    path?: never;
    query?: never;
    url: '/cart/remove-from-cart';
};

export type RemoveFromCartResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            itemsToRemove: CartItemEntity;
        };
        message: string;
    };
};

export type RemoveFromCartResponse = RemoveFromCartResponses[keyof RemoveFromCartResponses];

export type UpdateCartData = {
    body: {
        quantity: number;
        bagId: string;
    };
    path?: never;
    query?: never;
    url: '/cart/update-cart';
};

export type UpdateCartResponses = {
    /**
     * Ok
     */
    200: {
        data: CartItemEntity;
        message: string;
    };
};

export type UpdateCartResponse = UpdateCartResponses[keyof UpdateCartResponses];

export type GetCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart/get-cart';
};

export type GetCartResponses = {
    /**
     * Ok
     */
    200: {
        data: CartEntity | {
            cartItems: Array<unknown>;
        };
        message: string;
    };
};

export type GetCartResponse = GetCartResponses[keyof GetCartResponses];

export type AddBagData = {
    body: AddBagValidator;
    path?: never;
    query?: never;
    url: '/bag/add-bag';
};

export type AddBagResponses = {
    /**
     * Ok
     */
    200: {
        data: BagEntity;
        message: string;
        success: boolean;
    };
};

export type AddBagResponse = AddBagResponses[keyof AddBagResponses];

export type GetAllBagsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        search?: string;
        category?: string;
        minPrice?: number;
        maxPrice?: number;
    };
    url: '/bag/get-all-bags';
};

export type GetAllBagsResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            totalPages: number;
            page: number;
            total: number;
            data: Array<BagEntity>;
        };
        message: string;
        success: boolean;
    };
};

export type GetAllBagsResponse = GetAllBagsResponses[keyof GetAllBagsResponses];

export type GetBagByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/bag/get-bag/{id}';
};

export type GetBagByIdResponses = {
    /**
     * Ok
     */
    200: {
        data: BagEntity;
        message: string;
        success: boolean;
    };
};

export type GetBagByIdResponse = GetBagByIdResponses[keyof GetBagByIdResponses];

export type UpdateBagData = {
    body: UpdateBagValidator;
    path: {
        id: string;
    };
    query?: never;
    url: '/bag/update-bag/{id}';
};

export type UpdateBagResponses = {
    /**
     * Ok
     */
    200: {
        data: BagEntity;
        message: string;
        success: boolean;
    };
};

export type UpdateBagResponse = UpdateBagResponses[keyof UpdateBagResponses];

export type DeleteBagByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/bag/delete-bag/{id}';
};

export type DeleteBagByIdResponses = {
    /**
     * Ok
     */
    200: {
        data: BagEntity;
        message: string;
        success: boolean;
    };
};

export type DeleteBagByIdResponse = DeleteBagByIdResponses[keyof DeleteBagByIdResponses];

export type VerifyOtpData = {
    body: {
        email: string;
        otp: string;
    };
    path?: never;
    query?: never;
    url: '/auth/verify-otp';
};

export type VerifyOtpResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            fullName: string;
            email: string;
        };
        message: string;
        success: boolean;
    };
};

export type VerifyOtpResponse = VerifyOtpResponses[keyof VerifyOtpResponses];

export type ResendOtpData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/resend-otp';
};

export type ResendOtpResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            email: string;
        };
        message: string;
        success: boolean;
    };
};

export type ResendOtpResponse = ResendOtpResponses[keyof ResendOtpResponses];

export type RegisterUserData = {
    body: RegisterUserDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterUserResponses = {
    /**
     * Ok
     */
    200: RegisterResponse;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LoginUserData = {
    body: LoginValidator;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginUserResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            user: {
                fullName: string;
                email: string;
            };
        };
        message: string;
        success: boolean;
    };
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Ok
     */
    200: {
        message: string;
        success: boolean;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ResetPasswordData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetPasswordResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            email: string;
        };
        message: string;
        success: boolean;
    };
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type RecoverPasswordData = {
    body: {
        resetToken: string;
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/auth/recover-password';
};

export type RecoverPasswordResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            email: string;
        };
        message: string;
        success: boolean;
    };
};

export type RecoverPasswordResponse = RecoverPasswordResponses[keyof RecoverPasswordResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh-token';
};

export type RefreshTokenResponses = {
    /**
     * Ok
     */
    200: {
        message: string;
        success: boolean;
    };
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type GoogleAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type GoogleAuthResponses = {
    /**
     * No content
     */
    204: void;
};

export type GoogleAuthResponse = GoogleAuthResponses[keyof GoogleAuthResponses];

export type GoogleCallBackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/callback';
};

export type GoogleCallBackResponses = {
    /**
     * No content
     */
    204: void;
};

export type GoogleCallBackResponse = GoogleCallBackResponses[keyof GoogleCallBackResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};