// This file is auto-generated by @hey-api/openapi-ts

export type BagEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    name: string;
    price: number;
    description: string;
    categories: Array<Category>;
    bagImages: Array<MediaEntity>;
};

export type Category = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    categoryName: string;
    bags: Array<BagEntity>;
};

export type MediaEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    image: string;
    altText?: string;
    bag: BagEntity;
};

export type CreateCategoryValidator = {
    categoryName: string;
};

export type AddBagValidator = {
    name: string;
    price: number;
    description: string;
    categories: Array<string>;
};

export type UpdateBagValidator = {
    name?: string;
    price?: number;
    description?: string;
    categories?: Array<string>;
    bagImages?: Array<string>;
};

export type UploadMediaData = {
    body: {
        bagId: string;
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/media/upload';
};

export type UploadMediaResponses = {
    /**
     * Ok
     */
    200: {
        data?: unknown;
        message: string;
        success: boolean;
    } | {
        data: MediaEntity;
        message: string;
        success: boolean;
    };
};

export type UploadMediaResponse = UploadMediaResponses[keyof UploadMediaResponses];

export type AddCategoryData = {
    body: CreateCategoryValidator;
    path?: never;
    query?: never;
    url: '/category/add-category';
};

export type AddCategoryResponses = {
    /**
     * Ok
     */
    200: {
        data: Category;
        message: string;
        success: boolean;
    };
};

export type AddCategoryResponse = AddCategoryResponses[keyof AddCategoryResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/category/get-categories';
};

export type GetCategoriesResponses = {
    /**
     * Ok
     */
    200: {
        data: Array<Category>;
        message: string;
        success: boolean;
    };
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type GetCategoriesWithBagsData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        limit: number;
    };
    url: '/category/get-categories-with-bags';
};

export type GetCategoriesWithBagsResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            totalPages: number;
            page: number;
            total: number;
            data: Array<Category>;
        };
        message: string;
        success: boolean;
    };
};

export type GetCategoriesWithBagsResponse = GetCategoriesWithBagsResponses[keyof GetCategoriesWithBagsResponses];

export type AddBagData = {
    body: AddBagValidator;
    path?: never;
    query?: never;
    url: '/bag/add-bag';
};

export type AddBagResponses = {
    /**
     * Ok
     */
    200: {
        data: BagEntity;
        message: string;
        success: boolean;
    };
};

export type AddBagResponse = AddBagResponses[keyof AddBagResponses];

export type GetAllBagsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        search?: string;
        category?: string;
        minPrice?: number;
        maxPrice?: number;
    };
    url: '/bag/get-all-bags';
};

export type GetAllBagsResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            totalPages: number;
            page: number;
            total: number;
            data: Array<BagEntity>;
        };
        message: string;
        success: boolean;
    };
};

export type GetAllBagsResponse = GetAllBagsResponses[keyof GetAllBagsResponses];

export type GetBagByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/bag/get-bag/{id}';
};

export type GetBagByIdResponses = {
    /**
     * Ok
     */
    200: {
        data: BagEntity;
        message: string;
        success: boolean;
    };
};

export type GetBagByIdResponse = GetBagByIdResponses[keyof GetBagByIdResponses];

export type UpdateBagData = {
    body: UpdateBagValidator;
    path: {
        id: string;
    };
    query?: never;
    url: '/bag/update-bag/{id}';
};

export type UpdateBagResponses = {
    /**
     * Ok
     */
    200: {
        data: BagEntity;
        message: string;
        success: boolean;
    };
};

export type UpdateBagResponse = UpdateBagResponses[keyof UpdateBagResponses];

export type DeleteBagByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/bag/delete-bag/{id}';
};

export type DeleteBagByIdResponses = {
    /**
     * Ok
     */
    200: {
        data: BagEntity;
        message: string;
        success: boolean;
    };
};

export type DeleteBagByIdResponse = DeleteBagByIdResponses[keyof DeleteBagByIdResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};