// This file is auto-generated by @hey-api/openapi-ts

export type Category = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    categoryName: string;
    bags: Array<BagEntity>;
};

export type BagEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    name: string;
    price: number;
    description: string;
    categories: Array<Category>;
};

export type CreateCategoryValidator = {
    categoryName: string;
};

export type AddBagValidator = {
    name: string;
    price: number;
    description: string;
    categories: Array<string>;
};

export type AddCategoryData = {
    body: CreateCategoryValidator;
    path?: never;
    query?: never;
    url: '/category/add-category';
};

export type AddCategoryResponses = {
    /**
     * Ok
     */
    200: {
        data: Category;
        message: string;
        success: boolean;
    };
};

export type AddCategoryResponse = AddCategoryResponses[keyof AddCategoryResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/category/get-categories';
};

export type GetCategoriesResponses = {
    /**
     * Ok
     */
    200: {
        data: Array<Category>;
        message: string;
        success: boolean;
    };
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type AddBagData = {
    body: AddBagValidator;
    path?: never;
    query?: never;
    url: '/bag/add-bag';
};

export type AddBagResponses = {
    /**
     * Ok
     */
    200: {
        data: BagEntity;
        message: string;
        success: boolean;
    };
};

export type AddBagResponse = AddBagResponses[keyof AddBagResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};