/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AdminDashboardIndexImport } from './routes/admin-dashboard/index'
import { Route as AdminDashboardCategoryIndexImport } from './routes/admin-dashboard/category/index'
import { Route as AdminDashboardBagsIndexImport } from './routes/admin-dashboard/bags/index'
import { Route as AdminDashboardBagsViewBagsImport } from './routes/admin-dashboard/bags/viewBags'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardIndexRoute = AdminDashboardIndexImport.update({
  id: '/admin-dashboard/',
  path: '/admin-dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardCategoryIndexRoute =
  AdminDashboardCategoryIndexImport.update({
    id: '/admin-dashboard/category/',
    path: '/admin-dashboard/category/',
    getParentRoute: () => rootRoute,
  } as any)

const AdminDashboardBagsIndexRoute = AdminDashboardBagsIndexImport.update({
  id: '/admin-dashboard/bags/',
  path: '/admin-dashboard/bags/',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardBagsViewBagsRoute = AdminDashboardBagsViewBagsImport.update(
  {
    id: '/admin-dashboard/bags/viewBags',
    path: '/admin-dashboard/bags/viewBags',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard/': {
      id: '/admin-dashboard/'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard/bags/viewBags': {
      id: '/admin-dashboard/bags/viewBags'
      path: '/admin-dashboard/bags/viewBags'
      fullPath: '/admin-dashboard/bags/viewBags'
      preLoaderRoute: typeof AdminDashboardBagsViewBagsImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard/bags/': {
      id: '/admin-dashboard/bags/'
      path: '/admin-dashboard/bags'
      fullPath: '/admin-dashboard/bags'
      preLoaderRoute: typeof AdminDashboardBagsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard/category/': {
      id: '/admin-dashboard/category/'
      path: '/admin-dashboard/category'
      fullPath: '/admin-dashboard/category'
      preLoaderRoute: typeof AdminDashboardCategoryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/admin-dashboard/bags/viewBags': typeof AdminDashboardBagsViewBagsRoute
  '/admin-dashboard/bags': typeof AdminDashboardBagsIndexRoute
  '/admin-dashboard/category': typeof AdminDashboardCategoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/admin-dashboard/bags/viewBags': typeof AdminDashboardBagsViewBagsRoute
  '/admin-dashboard/bags': typeof AdminDashboardBagsIndexRoute
  '/admin-dashboard/category': typeof AdminDashboardCategoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/admin-dashboard/bags/viewBags': typeof AdminDashboardBagsViewBagsRoute
  '/admin-dashboard/bags/': typeof AdminDashboardBagsIndexRoute
  '/admin-dashboard/category/': typeof AdminDashboardCategoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/admin-dashboard/bags/viewBags'
    | '/admin-dashboard/bags'
    | '/admin-dashboard/category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/admin-dashboard/bags/viewBags'
    | '/admin-dashboard/bags'
    | '/admin-dashboard/category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin-dashboard/'
    | '/admin-dashboard/bags/viewBags'
    | '/admin-dashboard/bags/'
    | '/admin-dashboard/category/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardBagsViewBagsRoute: typeof AdminDashboardBagsViewBagsRoute
  AdminDashboardBagsIndexRoute: typeof AdminDashboardBagsIndexRoute
  AdminDashboardCategoryIndexRoute: typeof AdminDashboardCategoryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardBagsViewBagsRoute: AdminDashboardBagsViewBagsRoute,
  AdminDashboardBagsIndexRoute: AdminDashboardBagsIndexRoute,
  AdminDashboardCategoryIndexRoute: AdminDashboardCategoryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/admin-dashboard/",
        "/admin-dashboard/bags/viewBags",
        "/admin-dashboard/bags/",
        "/admin-dashboard/category/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/admin-dashboard/": {
      "filePath": "admin-dashboard/index.tsx"
    },
    "/admin-dashboard/bags/viewBags": {
      "filePath": "admin-dashboard/bags/viewBags.tsx"
    },
    "/admin-dashboard/bags/": {
      "filePath": "admin-dashboard/bags/index.tsx"
    },
    "/admin-dashboard/category/": {
      "filePath": "admin-dashboard/category/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
