/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AdminDashboardIndexImport } from './routes/admin-dashboard/index'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AdminDashboardCategoryIndexImport } from './routes/admin-dashboard/category/index'
import { Route as AdminDashboardBagsIndexImport } from './routes/admin-dashboard/bags/index'
import { Route as AuthRegisterVerifyOtpImport } from './routes/auth/register/verify-otp'
import { Route as AdminDashboardBagsAddBagImport } from './routes/admin-dashboard/bags/addBag'
import { Route as AdminDashboardBagsIdImport } from './routes/admin-dashboard/bags/$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardIndexRoute = AdminDashboardIndexImport.update({
  id: '/admin-dashboard/',
  path: '/admin-dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardCategoryIndexRoute =
  AdminDashboardCategoryIndexImport.update({
    id: '/admin-dashboard/category/',
    path: '/admin-dashboard/category/',
    getParentRoute: () => rootRoute,
  } as any)

const AdminDashboardBagsIndexRoute = AdminDashboardBagsIndexImport.update({
  id: '/admin-dashboard/bags/',
  path: '/admin-dashboard/bags/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterVerifyOtpRoute = AuthRegisterVerifyOtpImport.update({
  id: '/auth/register/verify-otp',
  path: '/auth/register/verify-otp',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardBagsAddBagRoute = AdminDashboardBagsAddBagImport.update({
  id: '/admin-dashboard/bags/addBag',
  path: '/admin-dashboard/bags/addBag',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardBagsIdRoute = AdminDashboardBagsIdImport.update({
  id: '/admin-dashboard/bags/$id',
  path: '/admin-dashboard/bags/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard/': {
      id: '/admin-dashboard/'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard/bags/$id': {
      id: '/admin-dashboard/bags/$id'
      path: '/admin-dashboard/bags/$id'
      fullPath: '/admin-dashboard/bags/$id'
      preLoaderRoute: typeof AdminDashboardBagsIdImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard/bags/addBag': {
      id: '/admin-dashboard/bags/addBag'
      path: '/admin-dashboard/bags/addBag'
      fullPath: '/admin-dashboard/bags/addBag'
      preLoaderRoute: typeof AdminDashboardBagsAddBagImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/verify-otp': {
      id: '/auth/register/verify-otp'
      path: '/auth/register/verify-otp'
      fullPath: '/auth/register/verify-otp'
      preLoaderRoute: typeof AuthRegisterVerifyOtpImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard/bags/': {
      id: '/admin-dashboard/bags/'
      path: '/admin-dashboard/bags'
      fullPath: '/admin-dashboard/bags'
      preLoaderRoute: typeof AdminDashboardBagsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard/category/': {
      id: '/admin-dashboard/category/'
      path: '/admin-dashboard/category'
      fullPath: '/admin-dashboard/category'
      preLoaderRoute: typeof AdminDashboardCategoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/admin-dashboard/bags/$id': typeof AdminDashboardBagsIdRoute
  '/admin-dashboard/bags/addBag': typeof AdminDashboardBagsAddBagRoute
  '/auth/register/verify-otp': typeof AuthRegisterVerifyOtpRoute
  '/admin-dashboard/bags': typeof AdminDashboardBagsIndexRoute
  '/admin-dashboard/category': typeof AdminDashboardCategoryIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/admin-dashboard/bags/$id': typeof AdminDashboardBagsIdRoute
  '/admin-dashboard/bags/addBag': typeof AdminDashboardBagsAddBagRoute
  '/auth/register/verify-otp': typeof AuthRegisterVerifyOtpRoute
  '/admin-dashboard/bags': typeof AdminDashboardBagsIndexRoute
  '/admin-dashboard/category': typeof AdminDashboardCategoryIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/admin-dashboard/bags/$id': typeof AdminDashboardBagsIdRoute
  '/admin-dashboard/bags/addBag': typeof AdminDashboardBagsAddBagRoute
  '/auth/register/verify-otp': typeof AuthRegisterVerifyOtpRoute
  '/admin-dashboard/bags/': typeof AdminDashboardBagsIndexRoute
  '/admin-dashboard/category/': typeof AdminDashboardCategoryIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/admin-dashboard/bags/$id'
    | '/admin-dashboard/bags/addBag'
    | '/auth/register/verify-otp'
    | '/admin-dashboard/bags'
    | '/admin-dashboard/category'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/admin-dashboard/bags/$id'
    | '/admin-dashboard/bags/addBag'
    | '/auth/register/verify-otp'
    | '/admin-dashboard/bags'
    | '/admin-dashboard/category'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin-dashboard/'
    | '/admin-dashboard/bags/$id'
    | '/admin-dashboard/bags/addBag'
    | '/auth/register/verify-otp'
    | '/admin-dashboard/bags/'
    | '/admin-dashboard/category/'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardBagsIdRoute: typeof AdminDashboardBagsIdRoute
  AdminDashboardBagsAddBagRoute: typeof AdminDashboardBagsAddBagRoute
  AuthRegisterVerifyOtpRoute: typeof AuthRegisterVerifyOtpRoute
  AdminDashboardBagsIndexRoute: typeof AdminDashboardBagsIndexRoute
  AdminDashboardCategoryIndexRoute: typeof AdminDashboardCategoryIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardBagsIdRoute: AdminDashboardBagsIdRoute,
  AdminDashboardBagsAddBagRoute: AdminDashboardBagsAddBagRoute,
  AuthRegisterVerifyOtpRoute: AuthRegisterVerifyOtpRoute,
  AdminDashboardBagsIndexRoute: AdminDashboardBagsIndexRoute,
  AdminDashboardCategoryIndexRoute: AdminDashboardCategoryIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/admin-dashboard/",
        "/admin-dashboard/bags/$id",
        "/admin-dashboard/bags/addBag",
        "/auth/register/verify-otp",
        "/admin-dashboard/bags/",
        "/admin-dashboard/category/",
        "/auth/login/",
        "/auth/register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/admin-dashboard/": {
      "filePath": "admin-dashboard/index.tsx"
    },
    "/admin-dashboard/bags/$id": {
      "filePath": "admin-dashboard/bags/$id.tsx"
    },
    "/admin-dashboard/bags/addBag": {
      "filePath": "admin-dashboard/bags/addBag.tsx"
    },
    "/auth/register/verify-otp": {
      "filePath": "auth/register/verify-otp.tsx"
    },
    "/admin-dashboard/bags/": {
      "filePath": "admin-dashboard/bags/index.tsx"
    },
    "/admin-dashboard/category/": {
      "filePath": "admin-dashboard/category/index.tsx"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
