/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin-dashboard/index'
import { Route as SearchIdRouteImport } from './routes/search/$id'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutResultRouteImport } from './routes/checkout/result'
import { Route as CheckoutEsewaCheckoutRouteImport } from './routes/checkout/esewa-checkout'
import { Route as BagIdRouteImport } from './routes/bag/$id'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthProtectedIndexRouteImport } from './routes/auth/protected/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AdminDashboardUsersIndexRouteImport } from './routes/admin-dashboard/users/index'
import { Route as AdminDashboardOrdersIndexRouteImport } from './routes/admin-dashboard/orders/index'
import { Route as AdminDashboardCategoryIndexRouteImport } from './routes/admin-dashboard/category/index'
import { Route as AdminDashboardBagsIndexRouteImport } from './routes/admin-dashboard/bags/index'
import { Route as AuthRegisterVerifyOtpRouteImport } from './routes/auth/register/verify-otp'
import { Route as AuthRecoverPasswordIdRouteImport } from './routes/auth/recover-password/$id'
import { Route as AuthLoginAdminLoginRouteImport } from './routes/auth/login/admin-login'
import { Route as AdminDashboardOrdersIdRouteImport } from './routes/admin-dashboard/orders/$id'
import { Route as AdminDashboardBagsAddBagRouteImport } from './routes/admin-dashboard/bags/addBag'
import { Route as AdminDashboardBagsIdRouteImport } from './routes/admin-dashboard/bags/$id'

const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin-dashboard/',
  path: '/admin-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIdRoute = SearchIdRouteImport.update({
  id: '/search/$id',
  path: '/search/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutResultRoute = CheckoutResultRouteImport.update({
  id: '/checkout/result',
  path: '/checkout/result',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutEsewaCheckoutRoute = CheckoutEsewaCheckoutRouteImport.update({
  id: '/checkout/esewa-checkout',
  path: '/checkout/esewa-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BagIdRoute = BagIdRouteImport.update({
  id: '/bag/$id',
  path: '/bag/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProtectedIndexRoute = AuthProtectedIndexRouteImport.update({
  id: '/auth/protected/',
  path: '/auth/protected/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardUsersIndexRoute =
  AdminDashboardUsersIndexRouteImport.update({
    id: '/admin-dashboard/users/',
    path: '/admin-dashboard/users/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardOrdersIndexRoute =
  AdminDashboardOrdersIndexRouteImport.update({
    id: '/admin-dashboard/orders/',
    path: '/admin-dashboard/orders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardCategoryIndexRoute =
  AdminDashboardCategoryIndexRouteImport.update({
    id: '/admin-dashboard/category/',
    path: '/admin-dashboard/category/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardBagsIndexRoute = AdminDashboardBagsIndexRouteImport.update({
  id: '/admin-dashboard/bags/',
  path: '/admin-dashboard/bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterVerifyOtpRoute = AuthRegisterVerifyOtpRouteImport.update({
  id: '/auth/register/verify-otp',
  path: '/auth/register/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverPasswordIdRoute = AuthRecoverPasswordIdRouteImport.update({
  id: '/auth/recover-password/$id',
  path: '/auth/recover-password/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginAdminLoginRoute = AuthLoginAdminLoginRouteImport.update({
  id: '/auth/login/admin-login',
  path: '/auth/login/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardOrdersIdRoute = AdminDashboardOrdersIdRouteImport.update({
  id: '/admin-dashboard/orders/$id',
  path: '/admin-dashboard/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardBagsAddBagRoute =
  AdminDashboardBagsAddBagRouteImport.update({
    id: '/admin-dashboard/bags/addBag',
    path: '/admin-dashboard/bags/addBag',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardBagsIdRoute = AdminDashboardBagsIdRouteImport.update({
  id: '/admin-dashboard/bags/$id',
  path: '/admin-dashboard/bags/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/bag/$id': typeof BagIdRoute
  '/checkout/esewa-checkout': typeof CheckoutEsewaCheckoutRoute
  '/checkout/result': typeof CheckoutResultRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/search/$id': typeof SearchIdRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/search': typeof SearchIndexRoute
  '/admin-dashboard/bags/$id': typeof AdminDashboardBagsIdRoute
  '/admin-dashboard/bags/addBag': typeof AdminDashboardBagsAddBagRoute
  '/admin-dashboard/orders/$id': typeof AdminDashboardOrdersIdRoute
  '/auth/login/admin-login': typeof AuthLoginAdminLoginRoute
  '/auth/recover-password/$id': typeof AuthRecoverPasswordIdRoute
  '/auth/register/verify-otp': typeof AuthRegisterVerifyOtpRoute
  '/admin-dashboard/bags': typeof AdminDashboardBagsIndexRoute
  '/admin-dashboard/category': typeof AdminDashboardCategoryIndexRoute
  '/admin-dashboard/orders': typeof AdminDashboardOrdersIndexRoute
  '/admin-dashboard/users': typeof AdminDashboardUsersIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/protected': typeof AuthProtectedIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/bag/$id': typeof BagIdRoute
  '/checkout/esewa-checkout': typeof CheckoutEsewaCheckoutRoute
  '/checkout/result': typeof CheckoutResultRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/search/$id': typeof SearchIdRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/search': typeof SearchIndexRoute
  '/admin-dashboard/bags/$id': typeof AdminDashboardBagsIdRoute
  '/admin-dashboard/bags/addBag': typeof AdminDashboardBagsAddBagRoute
  '/admin-dashboard/orders/$id': typeof AdminDashboardOrdersIdRoute
  '/auth/login/admin-login': typeof AuthLoginAdminLoginRoute
  '/auth/recover-password/$id': typeof AuthRecoverPasswordIdRoute
  '/auth/register/verify-otp': typeof AuthRegisterVerifyOtpRoute
  '/admin-dashboard/bags': typeof AdminDashboardBagsIndexRoute
  '/admin-dashboard/category': typeof AdminDashboardCategoryIndexRoute
  '/admin-dashboard/orders': typeof AdminDashboardOrdersIndexRoute
  '/admin-dashboard/users': typeof AdminDashboardUsersIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/protected': typeof AuthProtectedIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/bag/$id': typeof BagIdRoute
  '/checkout/esewa-checkout': typeof CheckoutEsewaCheckoutRoute
  '/checkout/result': typeof CheckoutResultRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/search/$id': typeof SearchIdRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/search/': typeof SearchIndexRoute
  '/admin-dashboard/bags/$id': typeof AdminDashboardBagsIdRoute
  '/admin-dashboard/bags/addBag': typeof AdminDashboardBagsAddBagRoute
  '/admin-dashboard/orders/$id': typeof AdminDashboardOrdersIdRoute
  '/auth/login/admin-login': typeof AuthLoginAdminLoginRoute
  '/auth/recover-password/$id': typeof AuthRecoverPasswordIdRoute
  '/auth/register/verify-otp': typeof AuthRegisterVerifyOtpRoute
  '/admin-dashboard/bags/': typeof AdminDashboardBagsIndexRoute
  '/admin-dashboard/category/': typeof AdminDashboardCategoryIndexRoute
  '/admin-dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/admin-dashboard/users/': typeof AdminDashboardUsersIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/protected/': typeof AuthProtectedIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/bag/$id'
    | '/checkout/esewa-checkout'
    | '/checkout/result'
    | '/checkout/success'
    | '/search/$id'
    | '/admin-dashboard'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/search'
    | '/admin-dashboard/bags/$id'
    | '/admin-dashboard/bags/addBag'
    | '/admin-dashboard/orders/$id'
    | '/auth/login/admin-login'
    | '/auth/recover-password/$id'
    | '/auth/register/verify-otp'
    | '/admin-dashboard/bags'
    | '/admin-dashboard/category'
    | '/admin-dashboard/orders'
    | '/admin-dashboard/users'
    | '/auth/login'
    | '/auth/protected'
    | '/auth/register'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/bag/$id'
    | '/checkout/esewa-checkout'
    | '/checkout/result'
    | '/checkout/success'
    | '/search/$id'
    | '/admin-dashboard'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/search'
    | '/admin-dashboard/bags/$id'
    | '/admin-dashboard/bags/addBag'
    | '/admin-dashboard/orders/$id'
    | '/auth/login/admin-login'
    | '/auth/recover-password/$id'
    | '/auth/register/verify-otp'
    | '/admin-dashboard/bags'
    | '/admin-dashboard/category'
    | '/admin-dashboard/orders'
    | '/admin-dashboard/users'
    | '/auth/login'
    | '/auth/protected'
    | '/auth/register'
    | '/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/forbidden'
    | '/bag/$id'
    | '/checkout/esewa-checkout'
    | '/checkout/result'
    | '/checkout/success'
    | '/search/$id'
    | '/admin-dashboard/'
    | '/cart/'
    | '/checkout/'
    | '/orders/'
    | '/profile/'
    | '/search/'
    | '/admin-dashboard/bags/$id'
    | '/admin-dashboard/bags/addBag'
    | '/admin-dashboard/orders/$id'
    | '/auth/login/admin-login'
    | '/auth/recover-password/$id'
    | '/auth/register/verify-otp'
    | '/admin-dashboard/bags/'
    | '/admin-dashboard/category/'
    | '/admin-dashboard/orders/'
    | '/admin-dashboard/users/'
    | '/auth/login/'
    | '/auth/protected/'
    | '/auth/register/'
    | '/auth/reset-password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForbiddenRoute: typeof ForbiddenRoute
  BagIdRoute: typeof BagIdRoute
  CheckoutEsewaCheckoutRoute: typeof CheckoutEsewaCheckoutRoute
  CheckoutResultRoute: typeof CheckoutResultRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  SearchIdRoute: typeof SearchIdRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  AdminDashboardBagsIdRoute: typeof AdminDashboardBagsIdRoute
  AdminDashboardBagsAddBagRoute: typeof AdminDashboardBagsAddBagRoute
  AdminDashboardOrdersIdRoute: typeof AdminDashboardOrdersIdRoute
  AuthLoginAdminLoginRoute: typeof AuthLoginAdminLoginRoute
  AuthRecoverPasswordIdRoute: typeof AuthRecoverPasswordIdRoute
  AuthRegisterVerifyOtpRoute: typeof AuthRegisterVerifyOtpRoute
  AdminDashboardBagsIndexRoute: typeof AdminDashboardBagsIndexRoute
  AdminDashboardCategoryIndexRoute: typeof AdminDashboardCategoryIndexRoute
  AdminDashboardOrdersIndexRoute: typeof AdminDashboardOrdersIndexRoute
  AdminDashboardUsersIndexRoute: typeof AdminDashboardUsersIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthProtectedIndexRoute: typeof AuthProtectedIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/': {
      id: '/admin-dashboard/'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$id': {
      id: '/search/$id'
      path: '/search/$id'
      fullPath: '/search/$id'
      preLoaderRoute: typeof SearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/result': {
      id: '/checkout/result'
      path: '/checkout/result'
      fullPath: '/checkout/result'
      preLoaderRoute: typeof CheckoutResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/esewa-checkout': {
      id: '/checkout/esewa-checkout'
      path: '/checkout/esewa-checkout'
      fullPath: '/checkout/esewa-checkout'
      preLoaderRoute: typeof CheckoutEsewaCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag/$id': {
      id: '/bag/$id'
      path: '/bag/$id'
      fullPath: '/bag/$id'
      preLoaderRoute: typeof BagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/protected/': {
      id: '/auth/protected/'
      path: '/auth/protected'
      fullPath: '/auth/protected'
      preLoaderRoute: typeof AuthProtectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/users/': {
      id: '/admin-dashboard/users/'
      path: '/admin-dashboard/users'
      fullPath: '/admin-dashboard/users'
      preLoaderRoute: typeof AdminDashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/orders/': {
      id: '/admin-dashboard/orders/'
      path: '/admin-dashboard/orders'
      fullPath: '/admin-dashboard/orders'
      preLoaderRoute: typeof AdminDashboardOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/category/': {
      id: '/admin-dashboard/category/'
      path: '/admin-dashboard/category'
      fullPath: '/admin-dashboard/category'
      preLoaderRoute: typeof AdminDashboardCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/bags/': {
      id: '/admin-dashboard/bags/'
      path: '/admin-dashboard/bags'
      fullPath: '/admin-dashboard/bags'
      preLoaderRoute: typeof AdminDashboardBagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/verify-otp': {
      id: '/auth/register/verify-otp'
      path: '/auth/register/verify-otp'
      fullPath: '/auth/register/verify-otp'
      preLoaderRoute: typeof AuthRegisterVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recover-password/$id': {
      id: '/auth/recover-password/$id'
      path: '/auth/recover-password/$id'
      fullPath: '/auth/recover-password/$id'
      preLoaderRoute: typeof AuthRecoverPasswordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/admin-login': {
      id: '/auth/login/admin-login'
      path: '/auth/login/admin-login'
      fullPath: '/auth/login/admin-login'
      preLoaderRoute: typeof AuthLoginAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/orders/$id': {
      id: '/admin-dashboard/orders/$id'
      path: '/admin-dashboard/orders/$id'
      fullPath: '/admin-dashboard/orders/$id'
      preLoaderRoute: typeof AdminDashboardOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/bags/addBag': {
      id: '/admin-dashboard/bags/addBag'
      path: '/admin-dashboard/bags/addBag'
      fullPath: '/admin-dashboard/bags/addBag'
      preLoaderRoute: typeof AdminDashboardBagsAddBagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/bags/$id': {
      id: '/admin-dashboard/bags/$id'
      path: '/admin-dashboard/bags/$id'
      fullPath: '/admin-dashboard/bags/$id'
      preLoaderRoute: typeof AdminDashboardBagsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForbiddenRoute: ForbiddenRoute,
  BagIdRoute: BagIdRoute,
  CheckoutEsewaCheckoutRoute: CheckoutEsewaCheckoutRoute,
  CheckoutResultRoute: CheckoutResultRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  SearchIdRoute: SearchIdRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  CartIndexRoute: CartIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  AdminDashboardBagsIdRoute: AdminDashboardBagsIdRoute,
  AdminDashboardBagsAddBagRoute: AdminDashboardBagsAddBagRoute,
  AdminDashboardOrdersIdRoute: AdminDashboardOrdersIdRoute,
  AuthLoginAdminLoginRoute: AuthLoginAdminLoginRoute,
  AuthRecoverPasswordIdRoute: AuthRecoverPasswordIdRoute,
  AuthRegisterVerifyOtpRoute: AuthRegisterVerifyOtpRoute,
  AdminDashboardBagsIndexRoute: AdminDashboardBagsIndexRoute,
  AdminDashboardCategoryIndexRoute: AdminDashboardCategoryIndexRoute,
  AdminDashboardOrdersIndexRoute: AdminDashboardOrdersIndexRoute,
  AdminDashboardUsersIndexRoute: AdminDashboardUsersIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthProtectedIndexRoute: AuthProtectedIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
